version: '3'
services:
  web-app:
    build: .
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:5000
    depends_on:
      - mssql-server
    command: dotnet watch run
    
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaSecreta@123
    ports: 
      - 1433:1433 